# Generated by Django 4.2.7 on 2024-05-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KitVerifierDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_checker', models.CharField(blank=True, max_length=100, null=True)),
                ('kit_physical_verifier', models.CharField(blank=True, max_length=100, null=True)),
                ('logistic_assigner', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
