# Generated by Django 4.2.7 on 2024-05-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderdispatch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KitVerifierDetails',
            new_name='LogisticDetails',
        ),
    ]
