# Generated by Django 4.2.7 on 2024-04-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_master', '0003_alter_assetmasteraccessories_box_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmasteraccessories',
            name='box_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
