# Generated by Django 4.2.7 on 2024-04-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_master', '0004_alter_assetmasteraccessories_box_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmasteraccessories',
            name='box_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
