# Generated by Django 4.2.7 on 2024-04-06 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderdetail_approver_email_orderdetail_checker_email'),
        ('requirements', '0004_requirementdetail_area_requirementdetail_asset_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementdetail',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='requirementdetail',
            name='r_customer',
        ),
        migrations.AddField(
            model_name='requirementdetail',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.customerdetail'),
        ),
        migrations.AddField(
            model_name='requirementdetail',
            name='order_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderdetail'),
        ),
    ]
