# Generated by Django 4.2.7 on 2024-04-06 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0005_remove_requirementdetail_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirementdetail',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
