# Generated by Django 4.2.7 on 2024-04-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0006_rename_customer_id_requirementdetail_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementdetail',
            name='relation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
