# Generated by Django 4.2.7 on 2024-04-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_assetss_orderdetail_assets'),
        ('requirements', '0007_alter_requirementdetail_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementdetail',
            name='customer',
        ),
        migrations.AddField(
            model_name='requirementdetail',
            name='customer',
            field=models.ManyToManyField(blank=True, related_name='req', to='orders.customerdetail'),
        ),
    ]
