# Generated by Django 4.2.7 on 2024-04-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0012_remove_requirementdetail_r_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementdetail',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='requirementdetail',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='requirementdetail',
            name='r_order_depdate',
        ),
        migrations.RemoveField(
            model_name='requirementdetail',
            name='r_order_enddate',
        ),
        migrations.RemoveField(
            model_name='requirementdetail',
            name='r_order_loc',
        ),
        migrations.RemoveField(
            model_name='requirementdetail',
            name='r_order_startdate',
        ),
    ]
