# Generated by Django 4.2.7 on 2024-04-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0014_requirementcust'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequirementCust',
        ),
    ]
