# Generated by Django 4.2.7 on 2024-04-07 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_assetss_orderdetail_assets'),
        ('requirements', '0015_delete_requirementcust'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementdetail',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.customerdetail'),
        ),
        migrations.AddField(
            model_name='requirementdetail',
            name='r_order_depdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirementdetail',
            name='r_order_enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirementdetail',
            name='r_order_loc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requirementdetail',
            name='r_order_startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
