# Generated by Django 4.2.7 on 2024-04-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0016_requirementdetail_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementdetail',
            name='box_number',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
