# Generated by Django 4.2.7 on 2024-04-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0017_alter_requirementdetail_box_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementdetail',
            name='r_order_loc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
