# Generated by Django 4.2.7 on 2024-04-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0020_remove_requirementdetail_box_number_requirementcust'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequirementCust',
        ),
    ]
