# Generated by Django 4.2.7 on 2024-04-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0020_requirementcust'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementcust',
            name='r_cust_id',
            field=models.IntegerField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='requirementdetail',
            name='r_unique_id',
            field=models.IntegerField(blank=True, max_length=10000, null=True),
        ),
    ]
