# Generated by Django 4.2.7 on 2024-04-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0021_requirementcust_r_cust_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementdetail',
            name='customer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
