# Generated by Django 4.2.7 on 2024-04-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0022_requirementdetail_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementdetail',
            name='customer',
            field=models.IntegerField(blank=True, max_length=10000, null=True),
        ),
    ]
