# Generated by Django 4.2.7 on 2024-04-10 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderdetail_req_id'),
        ('requirements', '0023_alter_requirementdetail_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementdetail',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.customerdetail'),
        ),
    ]
