# Generated by Django 4.2.7 on 2024-04-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0026_alter_requirementdetail_box_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementcust',
            name='r_cust_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='requirementdetail',
            name='box_number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requirementdetail',
            name='r_unique_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
