# Generated by Django 4.2.7 on 2024-04-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0027_alter_requirementcust_r_cust_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementdetail',
            name='box_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
