# Generated by Django 4.2.7 on 2024-04-12 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0022_requirementcust'),
        ('requirements', '0028_alter_requirementdetail_box_number'),
    ]

    operations = [
    ]
