# Generated by Django 4.2.7 on 2024-04-07 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderdetail_approver_email_orderdetail_checker_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='assets',
            new_name='assetss',
        ),
    ]
