# Generated by Django 4.2.7 on 2024-04-07 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_assets_orderdetail_assetss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='assetss',
            new_name='assets',
        ),
    ]
