# Generated by Django 4.2.7 on 2024-04-07 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0016_requirementdetail_customer_and_more'),
        ('orders', '0006_rename_assetss_orderdetail_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='req_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='requirements.requirementdetail'),
        ),
    ]
