# Generated by Django 4.2.7 on 2024-04-10 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0028_alter_requirementdetail_box_number'),
        ('orders', '0007_orderdetail_req_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='req_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='requirements.requirementcust'),
        ),
    ]
